# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VS1C_Xv-l514g69YHfODFcJNOnoxxikx
"""

""" importanción de librerias """
import pandas as pd
import seaborn as sb

""" conexión con la nube """
from google.colab import drive
drive.mount('/gdrive')

""" referencia de ruta """
path_ = "/gdrive/MyDrive/data_Cust_Mkt/dataset_banco.csv"

""" seteo del dataset en una variable """
dataf = pd.read_csv(path_)




""" INFO GENERAL DEL DATASET """
pd.read_csv(path_).info()

pd.read_csv(path_).head()

pd.read_csv(path_).shape

""" OTRA FORMA... """

dataf.info()

dataf.shape

